import s from './mint.module.css';
import { NavLink, useParams } from 'react-router-dom';
import { CAUSES_INFO } from '../../Utils/Constants/causes';
import TresNft from '../../Components/Tres-Nft/tres-nft';

import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import InputGroup from 'react-bootstrap/InputGroup';
import OverlayTrigger from 'react-bootstrap/OverlayTrigger';
import Tooltip from 'react-bootstrap/Tooltip';

import { BsFillInfoCircleFill } from "react-icons/bs";

import { useState } from 'react';

export default function Mint() {
  const { id }= useParams();
  const causes = CAUSES_INFO;
  const {title, description, image} = causes[id - 1];

  const [donateAll, setDonateAll] = useState(false);
  const [nftCount, setNftCount] = useState(1);
  //TODO INTERACTUAR CON REDUX
  const [btnText, setBtnText] = useState("Mint");
  const totalNfts = 1000;
  const minted = 500;
  

  const onCheck = () => {
    setDonateAll(!donateAll);
  }

  const mint = () => {
    //TODO Implementar Mint
    console.log("MINTEANDO....")
  }

  const change = (number) => {
    if ((number < 0 && nftCount > 1) || (number > 0 && nftCount < 10)) {
      setNftCount(nftCount + number);
    }
  }
  
  return(   
    <div className={s.container}>
      <p className="bigTitle">Cause {title} Mint</p>
      <TresNft causes={causes}/>
      <hr/>
      <div className={s.checkContainer}>
        <Form.Group className="mb-3" controlId="formBasicCheckbox">
          <Form.Check onChange={onCheck} type="checkbox" label="Donate All Profit" />
        </Form.Group>
        <OverlayTrigger
          key={"right"}
          placement={"right"}
          overlay={
            <Tooltip id={`tooltip-right`}>
              Check to give to your favorite cause the 100% profit generated by your NFT investment.
            </Tooltip>
          }
        >
        <Button className={s.info}><BsFillInfoCircleFill className={s.icon}/></Button>
        </OverlayTrigger>
      </div>
      
      <p>{minted + "/"  + totalNfts} Minted </p>
      <div className={s.mintDiv}>
        <InputGroup className={s.counter}>
          <Form.Control
            value={nftCount}
            placeholder=""
            aria-label="Recipient's username with two button addons"
            disabled
          />
          <Button onClick={() => change(-1)} variant="outline-secondary">-</Button>
          <Button onClick={() => change(+1)} variant="outline-secondary">+</Button>
        </InputGroup>
        <Button onClick={mint} className="generalBtn" variant="secondary">{btnText}</Button>
      </div>
    </div>
  )
}