//React
import { useParams } from 'react-router-dom';
import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';

//Bootstrap
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import InputGroup from 'react-bootstrap/InputGroup';
import OverlayTrigger from 'react-bootstrap/OverlayTrigger';
import Tooltip from 'react-bootstrap/Tooltip';

//Icons
import { BsFillInfoCircleFill } from "react-icons/bs";

//Style
import s from './mint.module.css';

//Local Components
import TresNft from '../../Components/Tres-Nft/tres-nft';

// Redux actions
import { getAllCauses } from '../../redux/actions'

export default function Mint() {
  const {container, checkContainer, info, mintDiv, counter, icon} = s;
  const { id }= useParams();
  //Dispatch
  const dispatch = useDispatch();
  useEffect(()=> {
    dispatch(getAllCauses());
  }, [ dispatch, id ]);
  const causes = useSelector(state => state.allCauses);

  const {title,  state} = causes[id - 1];

  const [donateAll, setDonateAll] = useState(false);
  const [nftCount, setNftCount] = useState(1);

  //TODO INTERACTUAR CON REDUX
  const totalNfts = 1000;
  const minted = 500;

  const onCheck = () => {
    setDonateAll(!donateAll);
  }

  const mint = () => {
    //TODO Implementar Mint
    console.log("MINTEANDO....")
  }

  const change = (number) => {
    if ((number < 0 && nftCount > 1) || (number > 0 && nftCount < 10)) {
      setNftCount(nftCount + number);
    }
  }
  
  return(   
    <div className={container}>
      <p className="bigTitle">Cause {title} Mint</p>
      <TresNft id={id} causes={causes}/>
      <hr/>
      <div className={checkContainer}>
        <Form.Group className="mb-3" controlId="formBasicCheckbox">
          <Form.Check onChange={onCheck} type="checkbox" label="Donate All Profit" />
        </Form.Group>
        <OverlayTrigger
          key={"right"}
          placement={"right"}
          overlay={
            <Tooltip id={`tooltip-right`}>
              Check to give to your favorite cause the 100% profit generated by your NFT investment.
            </Tooltip>
          }
        >
        <Button className={info}><BsFillInfoCircleFill className={icon}/></Button>
        </OverlayTrigger>
      </div>
      
      <p>{minted + "/"  + totalNfts} Minted </p>
      <div className={mintDiv}>
        <InputGroup className={counter}>
          <Form.Control
            value={nftCount}
            placeholder=""
            aria-label="Recipient's username with two button addons"
            disabled
          />
          <Button onClick={() => change(-1)} variant="outline-secondary">-</Button>
          <Button onClick={() => change(+1)} variant="outline-secondary">+</Button>
        </InputGroup>
        <Button onClick={mint} className="generalButton" variant="secondary" disabled={state === 'Soon'}>Mint</Button>
      </div>
    </div>
  )
}